language: objective-c
osx_image: xcode7

xcode_workspace: FancyFoodie.xcworkspace
xcode_scheme: FancyFoodie
xcode_sdk: iphonesimulator

before_install:
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
    - pod install
